#!/bin/bash

mkdir .git/cscope_lock 2>/dev/null || exit 0
basename=.git/cscope.out
trap "rmdir .git/cscope_lock; rm -f ${basename}.$$*" EXIT

cscope -b -q -f $basename.$$
for f in ${basename}.$$*; do
	if [[ "$f" =~ "${basename}".[[:digit:]]+\.(.*) ]]; then
		ext=${BASH_REMATCH[1]}
		echo $ext
		mv "$f" .git/cscope.out.$ext
	fi
done
rm -f .git/cscope.out.$$*
