#!/bin/bash
BRANCH_NAME=$(git branch | grep '*' | sed 's/* //')
if [ $BRANCH_NAME != '(no branch)' ]
then
    echo "# Last 5 commit messages" >> $1
    echo "# ----------------------" >> $1
    COMMITS=$(git log --pretty=format:"# %h %s [%an]" -5)
    echo "${COMMITS}" >> $1
    echo "#" >> $1
fi
TODO_added=$(git diff HEAD | awk_git_todo_added)
if [ -n "$TODO_added" ]; then
    echo "# TODO messages added" >> $1
    echo "# -------------------" >> $1
    IFS=$'\n'; for t in $TODO_added; do echo "# * $t" >> $1; done;
    echo "#" >> $1
fi
TODO_removed=$(git diff HEAD | awk_git_todo_removed)
if [ -n "$TODO_removed" ]; then
    echo "# TODO messages removed" >> $1
    echo "# ---------------------" >> $1
    IFS=$'\n'; for t in $TODO_removed; do echo "# * $t" >> $1; done;
    echo "#" >> $1
fi
