[".vim/pack/tpope/start/sensible"]
    type = "git-repo"
    url = "https://tpope.io/vim/sensible.git"
    refreshPeriod = "168h"
[".vim/pack/tpope/start/abolish"]
    type = "git-repo"
    url = "https://tpope.io/vim/abolish.git"
    refreshPeriod = "168h"
[".vim/pack/tpope/start/surround"]
    type = "git-repo"
    url = "https://tpope.io/vim/surround.git"
    refreshPeriod = "168h"
[".vim/pack/tpope/start/unimpaired"]
    type = "git-repo"
    url = "https://tpope.io/vim/unimpaired.git"
    refreshPeriod = "168h"
[".vim/pack/tpope/start/repeat"]
    type = "git-repo"
    url = "https://tpope.io/vim/repeat.git"
    refreshPeriod = "168h"
[".vim/pack/tpope/start/fugitive"]
    type = "git-repo"
    url = "https://tpope.io/vim/fugitive.git"
    refreshPeriod = "168h"
[".vim/pack/tpope/start/rhubarb"]
    type = "git-repo"
    url = "https://tpope.io/vim/rhubarb.git"
    refreshPeriod = "168h"
[".vim/pack/tpope/start/commentary"]
    type = "git-repo"
    url = "https://tpope.io/vim/commentary.git"
    refreshPeriod = "168h"
[".vim/pack/objects/start/vim-indent-object"]
    type = "git-repo"
    url = "https://github.com/michaeljsmith/vim-indent-object.git"
    refreshPeriod = "168h"
[".vim/pack/objects/start/vim-exchange"]
    type = "git-repo"
    url = "https://github.com/tommcdo/vim-exchange.git"
    refreshPeriod = "168h"
[".vim/pack/objects/start/vim-textobj-entire"]
    type = "git-repo"
    url = "https://github.com/kana/vim-textobj-entire.git"
    refreshPeriod = "168h"
[".vim/pack/motions/start/vim-paragraph-motion"]
    type = "git-repo"
    url = "https://github.com/dbakker/vim-paragraph-motion.git"
    refreshPeriod = "168h"
