[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "168h"

[".goenv"]
    type = "git-repo"
    url = "https://github.com/syndbg/goenv"
    refreshPeriod = "168h"

[".pyenv"]
    type = "git-repo"
    url = "https://github.com/pyenv/pyenv"
    refreshPeriod = "168h"

