[".vim/pack/tpope/start/sensible"]
    type = "git-repo"
    url = "https://tpope.io/vim/sensible.git"
    refreshPeriod = "168h"
[".vim/pack/tpope/start/abolish"]
    type = "git-repo"
    url = "https://tpope.io/vim/abolish.git"
    refreshPeriod = "168h"
[".vim/pack/tpope/start/unimpaired"]
    type = "git-repo"
    url = "https://tpope.io/vim/unimpaired.git"
    refreshPeriod = "168h"
[".vim/pack/tpope/start/repeat"]
    type = "git-repo"
    url = "https://tpope.io/vim/repeat.git"
    refreshPeriod = "168h"
[".vim/pack/tpope/start/fugitive"]
    type = "git-repo"
    url = "https://tpope.io/vim/fugitive.git"
    refreshPeriod = "168h"
[".vim/pack/tpope/start/rhubarb"]
    type = "git-repo"
    url = "https://tpope.io/vim/rhubarb.git"
    refreshPeriod = "168h"
[".vim/pack/tpope/start/surround"]
    type = "git-repo"
    url = "https://tpope.io/vim/surround.git"
    refreshPeriod = "168h"

