[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "168h"

[".nvm"]
    type = "git-repo"
    url = "https://github.com/nvm-sh/nvm"
    refreshPeriod = "168h"
