#!/bin/bash

ALL_OFF="$(tput sgr0)"
BOLD="$(tput bold)"
GREEN="${BOLD}$(tput setaf 2)"
YELLOW="${BOLD}$(tput setaf 3)"
RED="${BOLD}$(tput setaf 1)"
WHITE="${BOLD}$(tput setaf 7)"

err() {
    printf "${RED}error: ${ALL_OFF}${1}\n" >&2
}

warn() {
    printf "${YELLOW}warning: ${ALL_OFF}${1}\n" >&2
}

msg() {
    local mesg=$1; shift
    printf "${GREEN}==> ${WHITE}${mesg}${ALL_OFF}\n" "$*" >&2
}

link() {
    local target="$2"
    [[ -z $2 ]] && target=".${1##*/}" \

    if [[ -e "$target" && ! -h "$target" ]]; then
	warn "$target exists in filesystem"
	return
    fi

    [[ -d "$target" ]] && rm "$target"
    ln -fs "$root/$1" "$target"
}

# Deploy scriptlets
df_bin()            { link bin .local/bin;                                  }
df_cower()          { link cower .config/cower;                             }
df_gtk3()           { link gtk-3.0 .config/gtk-3.0;                         }
df_pam()            { link pam/pam_environment;                             }
df_ranger()         { link ranger .config/ranger;                           }
df_makepkg()        { link makepkg/makepkg.conf;                            }
df_user-dirs()      { link user-dirs/user-dirs.dirs .config/user-dirs.dirs; }

df_emacs(){
    link emacs .emacs.d
}

df_git(){
    link git/gitconfig
    link git
}

df_shell(){
    link shell/prezto ${HOME}/.zprezto
    link shell/zlogin
    link shell/zprofile
    link shell/zshenv
    link shell/zshrc
    link shell/zpreztorc
    link shell/zlogout
}


root=$PWD
dotfiles=($(compgen -A function df_))

usage() {
    cat << HERE
Automated deploy function for dotfile syncronization.

SUPPORTED:
HERE

    printf '%s\n' ${dotfiles[@]#df_} | column
    exit ${1:-0}
}

deploy() {
    while (( $# )); do
	local fun=${1#df_}
	
	msg "Deploying $fun..."
	if ! declare -f df_$fun >/dev/null; then
	    err "don't know how to deploy \"$1\""
	    usage >&2 1
	fi

	(cd $HOME && df_$fun)
	shift
    done
}

if (( $# == 0 )); then
    deploy ${dotfiles[@]}
elif [[ "$1" =~ -h|--help ]]; then
    usage 0
else
    deploy $*
fi
