library: /home/jdahm/Music/Library/music.blb
directory: /home/jdahm/Music/Library
threaded: yes
color: yes
plugins: scrub fetchart lastgenre
paths:
  default: $albumartist/$album%aunique{}/$track-$title
  singleton: Non-Album/$artist/$title
  comp: Compilations/$album%aunique{}/$track-$title
  albumtype:soundtrack: Soundtracks/$album/$track-$title